### ISSUE TITLE
Can't get Git By a Bus to work

### ISSUE THREAD

**Issue by tcreeds** [tcreeds/commarch-report#3]
Git By a Bus fails when I run it. I've spent quite a while now calling different arguments, using different versions of python, and so forth. This is the most recent stack trace, with python 2.6.5, which the dev says has been known to work.

C:\Users\Trevor\Documents\projects\git_by_a_bus>python git_by_a_bus.py -v -c --python-exe=C:\Python26 C:\Users\Trevor\documents\projects\hfoss
Input file is: None
Output file is: C:\Users\Trevor\Documents\projects\git_by_a_bus\output\gen_file_stats.tsv
['C:\Python26', 'C:\Users\Trevor\Documents\projects\git_by_a_bus\gen_file_stats.py', 'C:\Users\Trevor\documents\projects\hfoss']
Traceback (most recent call last):
  File "git_by_a_bus.py", line 210, in <module>
    main(options.python_exe, paths_projects, options)
  File "git_by_a_bus.py", line 151, in main
    run_chained(cmd_ts, python_cmd, output_dir, options.verbose)
  File "git_by_a_bus.py", line 78, in run_chained
    cmd_p = Popen(cmd, stdin=input_f, stdout=output_f)
  File "C:\Python26\lib\subprocess.py", line 633, in **init**
    errread, errwrite)
  File "C:\Python26\lib\subprocess.py", line 842, in _execute_child
    startupinfo)
WindowsError: [Error 5] Access is denied

**Comment by ghost** [comment]
On Mon, Oct 10, 2016 at 04:07:47PM -0700, tcreeds wrote:

> Git By a Bus fails when I run it. I've spent quite a while now calling
> different arguments, using different versions of python, and so forth. This is
> the most recent stack trace, with python 2.6.5, which the dev says has been
> known to work.
> 
> C:\Users\Trevor\Documents\projects\git_by_a_bus>python git_by_a_bus.py -v -c
> --python-exe=C:\Python26 C:\Users\Trevor\documents\projects\hfoss
> Input file is: None
> Output file is: C:\Users\Trevor\Documents\projects\git_by_a_bus\output\
> gen_file_stats.tsv
> ['C:\Python26', 'C:\Users\Trevor\Documents\projects\git_by_a_bus\
> gen_file_stats.py', 'C:\Users\Trevor\documents\projects\hfoss']
> Traceback (most recent call last):
> File "git_by_a_bus.py", line 210, in
> main(options.python_exe, paths_projects, options)
> File "git_by_a_bus.py", line 151, in main
> run_chained(cmd_ts, python_cmd, output_dir, options.verbose)
> File "git_by_a_bus.py", line 78, in run_chained
> cmd_p = Popen(cmd, stdin=input_f, stdout=output_f)
> File "C:\Python26\lib\subprocess.py", line 633, in init
> errread, errwrite)
> File "C:\Python26\lib\subprocess.py", line 842, in _execute_child
> startupinfo)
> WindowsError: [Error 5] Access is denied

Does

C:\Users\Trevor\Documents\projects\git_by_a_bus\output\

exist?

And is it empty at the start of the run?

Alternately, folks have been able to run git-by-a-truck, and while it
calculates the metrics does not complete the full report, so you'd have to
pull that out yourself.

## 

Joe

**Comment by ghost** [comment]
One tip: When troubleshooting gbab/gbat, run them on themselves, since they
are usually relatively small compared to other things we tend to look at.

## 

Joe

**Comment by tcreeds** [comment]
I got it to run successfully, but it hits the memory issue with Godot. I'm attempting to get Git by a truck up and running, but now I'm having issues installing pygit2. Sort of makes me wish I wasn't using Windows.

**Comment by adf5051** [comment]
@tcreeds did you end up getting GBAT working? I will try to get it up and running too if you haven't

**Comment by tcreeds** [comment]
No, I'm still having issues with pygit2. I've made progress, it gets through more of the installation before breaking. It's currently failing to link a bunch of files from libgit2, so hopefully I can get that resolved.

Git by a Bus ran out of memory on all three projects, so I think GBAT is our only choice.

**Comment by tcreeds** [comment]
Update: found a wheel of pygit2 at http://www.lfd.uci.edu/~gohlke/pythonlibs/#pygit2

It installs, and I was able to install GBAT, but then I ran into another problem: there's no documentation on how to actually use it. Will attempt to figure it out later tonight.

**Comment by ghost** [comment]
On Tue, Oct 11, 2016 at 01:43:58PM -0700, tcreeds wrote:

> Update: found a wheel of pygit2 at http://www.lfd.uci.edu/~gohlke/pythonlibs/#
> pygit2
> 
> It installs, and I was able to install GBAT, but then I ran into another
> problem: there's no documentation on how to actually use it. Will attempt to
> figure it out later tonight.

:+1:

Sounds like using the time productively. Let's aim for having something out
of this by Thursday.

This also gives @PatrickGormley and @adf5051 some more time to jump in.

**Comment by tcreeds** [comment]
From what I can tell, usage is "gitbyatruck run" in the project directory that you want to analyze, with development.ini copied over from the gitbyatruck source directory. 

I'm getting an error with "refs/heads/master" not getting found by pygit2, which I think is because I fudged the requirements file from pygit2==0.21.1 to pygit2>=0.21.1 to allow for my 0.24.1 version, which is the only working version I was able to get. I'll ask ryansb in IRC tomorrow.

**Comment by adf5051** [comment]
I have had the most luck with GBAB but it never finishes. I am having difficulty with GBAT but it seems like you are closer to getting it to work than I am. I will continue to poke at GBAT and some of the forks. Other than that I will just keep chugging on the questions and research.

**Comment by tcreeds** [comment]
I've pretty much given up on GBAT. GBAB runs out of memory on my laptop, but I'll try to get it running on a lab machine and see if I can finish at least one of them. Can you post what you have for questions and research? My most recent stuff is up for Godot and Drupal, and it still needs sources, but aside from that it's in pretty good shape. I haven't even looked at Empathy.

**Comment by adf5051** [comment]
http://forked.yannick.io/tomheon/git_by_a_bus

I used that service to get a list of the GBAB forks and it seems like the original is the most up to date and maintained. I am playing around with his v2 feature branch to see if it works right now.

**Comment by adf5051** [comment]
So, the v2 branch seems to work, but I need to dig a bit deeper to make sure it actually is. the out put is in a different format (I'm assuming that its not finished and that the visual report was never completed) and so I need to parse some json. To run it you run python gbab.py ./path/to/repo you may need to pip install pygments to make it work. It also seems to dislike python 3 so i'm running it with python 2.7

**Comment by adf5051** [comment]
So I added the output from gbab for godot on my repo, can someone pull it down and see if all of the files are there? I think github rejected a lot of the files because of how many there are so I may need to package it up in some way so that everything is there.
